name       : ksystemstats
version    : 5.22.1
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.22.1/ksystemstats-5.22.1.tar.xz : 904b64c3cb1e61ddfb968d720d41ad1f4e94927049419d74b16700956879befb
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnm)
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - lm_sensors-devel
    - networkmanager-qt-devel
rundeps    :
    - libksysguard
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
