name       : ksystemstats
version    : 5.23.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.1/ksystemstats-5.23.1.tar.xz : e603659096d6f1da02dd8aa68f7ed211c0ce84f49450c8d769e567480f786a7e
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnm)
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - lm_sensors-devel
    - networkmanager-qt-devel
rundeps    :
    - libksysguard
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
