name       : ksystemstats
version    : 5.27.5
release    : 22
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/ksystemstats-5.27.5.tar.xz : d59d84cdf8c9cd8a2c3639ebb5986f50995f1f7f74a833af867709b7c336dcf8
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - lm_sensors-devel
    - networkmanager-qt-devel
rundeps    :
    - libksysguard
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
