name       : ksystemstats
version    : 5.24.5
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.5/ksystemstats-5.24.5.tar.xz : 0bacd8f8a494addb4afa37d59236429f8898ab5b80882abde44f41182aa759f7
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnm)
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - lm_sensors-devel
    - networkmanager-qt-devel
rundeps    :
    - libksysguard
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
